
-- This file has been automatically generated by SimUAid.

library ieee;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

library SimUAid_synthesis_Package;
use SimUAid_synthesis_Package.SimuAid_synthesis_pack.all;

entity Lab3 is
port(A, B, C, D, E: in STD_LOGIC;

	W, X, Y, Z: out STD_LOGIC
	);
end Lab3;

architecture Structure of Lab3 is
	signal B_p, Vnet_0, Vnet_1, Vnet_2, A_p, D_p, Vnet_3, Vnet_4, Vnet_5, Vnet_6, 
		E_p, Vnet_7, Vnet_8, Vnet_9, Vnet_10, Vnet_11, Vnet_12, Vnet_13, C_p: STD_LOGIC;
begin
	VHDL_Device_0: nor3 port map (A, B, C, Vnet_0);
	VHDL_Device_1: nor3 port map (B_p, C, E, Vnet_2);
	VHDL_Device_2: nor2 port map (C, D, Vnet_1);
	VHDL_Device_3: nor3 port map (Vnet_0, Vnet_1, Vnet_2, W);
	VHDL_Device_4: inverter port map (A, A_p);
	VHDL_Device_5: inverter port map (B, B_p);
	VHDL_Device_6: inverter port map (C, C_p);
	VHDL_Device_7: inverter port map (D, D_p);
	VHDL_Device_8: inverter port map (E, E_p);
	VHDL_Device_9: nor3 port map (A, B, D, Vnet_3);
	VHDL_Device_10: nor3 port map (B_p, C, E_p, Vnet_4);
	VHDL_Device_11: nor3 port map (A_p, C, E, Vnet_5);
	VHDL_Device_12: nor3 port map (B_p, C, D, Vnet_6);
	VHDL_Device_13: nor4 port map (Vnet_3, Vnet_4, Vnet_5, Vnet_6, X);
	VHDL_Device_14: nor3 port map (A, B, E, Vnet_7);
	VHDL_Device_15: nor3 port map (A_p, C, D, Vnet_8);
	VHDL_Device_16: nor3 port map (B_p, D, E, Vnet_10);
	VHDL_Device_17: nor4 port map (B_p, C, D_p, E_p, Vnet_9);
	VHDL_Device_18: nor4 port map (Vnet_7, Vnet_8, Vnet_9, Vnet_10, Y);
	VHDL_Device_19: nor2 port map (A, B, Vnet_11);
	VHDL_Device_20: nor2 port map (C, E, Vnet_12);
	VHDL_Device_21: nor3 port map (B_p, D, E, Vnet_13);
	VHDL_Device_22: nor3 port map (Vnet_11, Vnet_12, Vnet_13, Z);
end Structure;