
-- This file has been automatically generated by SimUAid.

library ieee;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

library SimUAid_synthesis;
use SimUAid_synthesis.SimuAid_synthesis_pack.all;

entity SM is
port(rst, X, clk: in STD_LOGIC;

	Z, Q1, Q2, Q3: out STD_LOGIC
	);
end SM;

architecture Structure of SM is
	signal Vnet_0, Vnet_1, Vnet_2, Vnet_3, Q1_p, Vnet_4, Vnet_5, Vnet_6, Vnet_7, X_p, 
		Vnet_8, Vnet_9, Vnet_10, Vnet_11, Q3_p, Vnet_12, Vnet_13, Vnet_14, Q2_p, Vnet_15: STD_LOGIC;
begin
	VHDL_Device_0: Dflipflop port map (clk, Vnet_5, Vnet_6, rst, Vnet_13, Q1_p);
	VHDL_Device_1: Dflipflop port map (clk, Vnet_3, Vnet_7, rst, Vnet_12, Q2_p);
	VHDL_Device_2: Dflipflop port map (clk, Vnet_4, Vnet_15, rst, Vnet_14, Q3_p);
	VHDL_Device_3: nand2 port map (Vnet_2, X, Vnet_4);
	VHDL_Device_4: nand2 port map (Vnet_13, Vnet_14, Vnet_2);
	VHDL_Device_5: nand2 port map (Vnet_14, X_p, Vnet_0);
	VHDL_Device_6: nand2 port map (Q2_p, Vnet_14, Vnet_1);
	VHDL_Device_7: nand3 port map (Vnet_0, Vnet_1, Vnet_2, Vnet_5);
	VHDL_Device_8: nand3 port map (Vnet_12, X_p, Q3_p, Vnet_3);
	VHDL_Device_9: nor3 port map (Q1_p, Vnet_14, X, Z);
	VHDL_Device_10: inverter port map (X, X_p);
	Q2 <= Vnet_12;
	Q1 <= Vnet_13;
	Q3 <= Vnet_14;
	Vnet_15 <= 'Z';
	Vnet_6 <= '1';
	Vnet_7 <= '1';
	Vnet_9 <= '1';
end Structure;